version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/superapiv1db
      SPRING_DATASOURCE_USERNAME: superuser
      SPRING_DATASOURCE_PASSWORD: superpassword
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: superapiv1db
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
